name: .NET CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      working-directory: SchoolApplication
      run: dotnet restore SchoolApplication.sln

    - name: Build solution
      working-directory: SchoolApplication
      run: dotnet build SchoolApplication.sln --no-restore

    - name: Run Unit Tests with Code Coverage
      run: |
        dotnet test SchoolApplication.Tests/SchoolApplication.Tests.csproj `
          --no-build `
          --verbosity normal `
          --collect:"XPlat Code Coverage" `
          --results-directory ./TestResults `
          /p:CollectCoverage=true `
          /p:CoverletOutputFormat=opencover `
          /p:CoverletOutput=./coverage/coverage.xml
      working-directory: SchoolApplication

    - name: Install ReportGenerator
      run: dotnet tool install -g ReportGenerator

    - name: Generate Code Coverage Report
      run: reportgenerator `
        "-reports:./coverage/coverage.xml" `
        "-targetdir:./coverage_report" `
        "-reporttypes:Html"
      working-directory: SchoolApplication

    - name: Upload Code Coverage Report

      uses: actions/upload-artifact@v4
      with:
        name: Code-Coverage-Report
        path: SchoolApplication/coverage_report/
        retention-days: 7
