name: .NET CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      working-directory: SchoolApplication
      run: dotnet restore SchoolApplication.sln

    - name: Build solution
      working-directory: SchoolApplication
      run: dotnet build SchoolApplication.sln --no-restore

    - name: Install Coverlet and ReportGenerator
      run: |
        dotnet tool install --global coverlet.console --version 6.0.0
        dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.3.0

    - name: Run Unit Tests with Coverage
      working-directory: SchoolApplication
      run: dotnet test SchoolApplication.Tests/SchoolApplication.Tests.csproj --collect:"XPlat Code Coverage" --settings "test.runsettings" --results-directory "./TestResults" --logger "trx" --verbosity normal

    - name: Generate Coverage Report
      working-directory: SchoolApplication
      run: |
        reportgenerator "-reports:./TestResults/**/coverage.cobertura.xml" "-targetdir:./CoverageReport" "-reporttypes:Html" "-assemblyfilters:+SchoolApplication.ViewModels" "-filefilters:-*Tests;+*;-*Migrations*"

    - name: Upload Coverage Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CodeCoverageReport
        path: SchoolApplication/CoverageReport/
        retention-days: 5
